siteName: Top Key Math
description: Data science courses developed by Samuel S. Watson and the Brown University Data Science Initiative
locales: [en, de]

header:
  logo: selfkey.svg
  titleString: Top Key Math

search:
  enabled: false

tutor:
  #enabled: true
  name: Bruno
  icon: bruno.svg #기본경로 frontend\assets

footer:
  rows:
    - links:
        - title: GitHub
          url: https://mathbus.co.kr/main/
        - title: Top Key Pub
          url: https://mathbus.co.kr/main/
        - title: Live Website
          url: https://mathbus.co.kr/main/
  copyright: CC-BY-2.0 License

social:
  facebook:
    page: https://mathbus.co.kr/main/
  twitter:
    handle: https://mathbus.co.kr/main/

courses:
  showLocked: true
  revealAll: false
  audio: false